AllCops:
  TargetRubyVersion: 2.7.1
  Exclude:
    - tmp/**/*
    - lib/bundler/vendor/**/*
    - db/**/*.rb
    - config/application.rb
    - config/environments/*.rb
    - public/**/**
  DisplayCopNames: true
  NewCops: enable

Style/Documentation:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/MethodLength:
  Max: 50

Metrics/BlockLength:
  Max: 30
  Exclude:
  - spec/**/*

Metrics/BlockNesting:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

# Security
Security/Eval:
  Enabled: true
  Exclude:
  - app/controllers/authentication_controller.rb
