default: &default
  adapter: postgresql
  pool: 5
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  port: <%= ENV.fetch('DATABASE_PORT', 5432) %>

development:
  <<: *default
  database:  <%= ENV["DATABASE_NAME"] %>

test:
  <<: *default
  database: <%= ENV["DATABASE_NAME"] %>

production:
  <<: *default
  database:  <%= ENV["DATABASE_NAME"] %>
