name: Api Service
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0.0'
    - name: Install dependencies
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 1
    - name: Run RuboCop
      run: bundle exec rubocop
    # - name: Run tests
      # run: bundle exec rspec