name: Api Service
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      continue-on-error: false
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0.0'
      continue-on-error: false
    - name: Install dependencies
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 1
      continue-on-error: false
    - name: Run RuboCop
      run: bundle exec rubocop
      continue-on-error: false
    # - name: Run tests
      # run: bundle exec rspec